version: 2.1

orbs:
  node: circleci/node@5.1.0
  ruby: circleci/ruby@2.1.1
  macos: circleci/macos@2

jobs:
  react-native-test:
    docker:
      - image: cimg/node:20.10
    environment:
      CI: true

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
            - npm-v1-{{ arch }}

      - restore_cache:
          keys:
            - node-modules-v1-{{ checksum "package.json" }}-{{ arch }}
            - node-modules-v1-{{ arch }}

      - run: npm install
      - run: npm test
      - run: npm run tsc

      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - ~/.npm
          when: always

      - save_cache:
          key: node-modules-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
          when: always

  macos-build-and-deploy:
    macos:
      xcode: 15.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta
      # These environment variables should be set in CircleCI project settings:
      # ASC_KEY_ID: App Store Connect API Key ID
      # ASC_ISSUER_ID: App Store Connect API Issuer ID
      # ASC_KEY_CONTENT: App Store Connect API Key Content (base64 encoded)
      # APPLE_TEAM_ID: Your Apple Developer Team ID
      # For Android builds:
      # ANDROID_KEYSTORE_FILE: Path to your keystore file
      # ANDROID_KEYSTORE_PASSWORD: Your keystore password
      # ANDROID_KEY_ALIAS: Your key alias
      # ANDROID_KEY_PASSWORD: Your key password
      # GOOGLE_PLAY_JSON_KEY: Path to your Google Play JSON key file
      # Required Ruby/OpenSSL environment variables
      
      # APP_STORE_CONNECT_API_KEY: App Store Connect API Key (base64 encoded)
      # IOS_PRIVATE_KEY:  iOS distribution certificate private key (base64 encoded)

    steps:
      - checkout
      
      - run:
          name: Create Lock Files
          command: |
            # Create empty lock files to prevent cache errors
            touch Gemfile.lock
            mkdir -p ios
            touch ios/Podfile.lock
      
      - run:
          name: Setup Ruby 3.0.0
          command: |
            # Install Ruby 3.0.0 with rbenv
            rbenv install 3.0.0 -s
            rbenv global 3.0.0
            rbenv rehash
            echo "Ruby version:"
            ruby -v
            
      - run:
          name: Ruby and Bundler Info
          command: |
            ruby -v
            gem install bundler -v 2.3.20 --user-install
            export GEM_HOME="$HOME/.gem"
            export PATH="$GEM_HOME/ruby/$(ruby -e 'puts RUBY_VERSION')/bin:$HOME/.local/share/gem/ruby/$(ruby -e 'puts RUBY_VERSION')/bin:$PATH"
            bundler -v
            
      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
            - npm-v1-{{ arch }}

      - restore_cache:
          keys:
            - node-modules-v1-{{ checksum "package.json" }}-{{ arch }}
            - node-modules-v1-{{ arch }}

      - run: npm install

      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - ~/.npm
          when: always

      - save_cache:
          key: node-modules-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
          when: always

      - run:
          name: Initialize Gemfile.lock if missing
          command: |
            if [ ! -f Gemfile.lock ]; then
              touch Gemfile.lock
            fi

      - restore_cache:
          keys:
            - ruby-gems-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
            - ruby-gems-v1-{{ arch }}

      - run:
          command: |
            export GEM_HOME="$HOME/.gem"
            export PATH="$GEM_HOME/ruby/$(ruby -e 'puts RUBY_VERSION')/bin:$HOME/.local/share/gem/ruby/$(ruby -e 'puts RUBY_VERSION')/bin:$PATH"
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
          working_directory: .

      - save_cache:
          key: ruby-gems-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
          when: always

      - run:
          name: Generate Native Code from Expo
          command: npx expo prebuild --clean

      - restore_cache:
          keys:
            - pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}
            - pods-v1-{{ arch }}

      - run:
          command: pod install
          working_directory: ios

      - save_cache:
          key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}
          paths:
            - ios/Pods
          when: always

      - run:
          name: Deploy to TestFlight
          command: sh fastlane/deploy-ios.sh

      - store_artifacts:
          path: output
          destination: ios-build
      
      - store_artifacts:
          path: fastlane/screenshots
          destination: screenshots

  android-build-and-deploy:
    working_directory: ~/expo-react-native-paper
    docker:
      - image: cimg/android:2023.09-node
    environment:
      # These environment variables should be set in CircleCI project settings:
      # ANDROID_KEYSTORE_PASSWORD: Your keystore password
      # ANDROID_KEY_ALIAS: Your key alias
      # ANDROID_KEY_PASSWORD: Your key password
      # ANDROID_PLAY_STORE_CREDENTIALS: Google Play Store credentials (base64 encoded)
      # ANDROID_SIGNING_KEY: Android keystore file (base64 encoded)
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dorg.gradle.parallel=false"
      TERM: dumb
      
    steps:
      - checkout:
          path: ~/expo-react-native-paper

      - run:
          name: Create Required Files
          command: |
            echo "Creating initial required files..."
            touch Gemfile.lock
            mkdir -p android/app
            echo "// Placeholder until expo prebuild creates the real files" > android/build.gradle
            echo "// Placeholder until expo prebuild creates the real files" > android/app/build.gradle

      - attach_workspace:
          at: ~/expo-react-native-paper

      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
            - npm-v1-{{ arch }}

      - restore_cache:
          keys:
            - node-modules-v1-{{ checksum "package.json" }}-{{ arch }}
            - node-modules-v1-{{ arch }}

      - run: npm install

      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - ~/.npm
          when: always

      - save_cache:
          key: node-modules-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
          when: always

      - run:
          name: Install Ninja
          command: sudo apt-get update && sudo apt-get install -y ninja-build
          
      - run:
          name: Initialize Gemfile.lock if missing
          command: |
            if [ ! -f Gemfile.lock ]; then
              touch Gemfile.lock
            fi

      - restore_cache:
          keys:
            - ruby-gems-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
            - ruby-gems-v1-{{ arch }}

      - run:
          command: |
            export GEM_HOME="$HOME/.gem"
            export PATH="$GEM_HOME/ruby/$(ruby -e 'puts RUBY_VERSION')/bin:$HOME/.local/share/gem/ruby/$(ruby -e 'puts RUBY_VERSION')/bin:$PATH"
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
          working_directory: .

      - save_cache:
          key: ruby-gems-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
          when: always

      - run:
          name: Setup Android SDK
          command: |
            echo "Installing SDK Tools"
            yes | sdkmanager --licenses || true
            yes | sdkmanager "platform-tools" "build-tools;33.0.1" "platforms;android-33" "ndk;21.0.6113669" || true
            
      - run:
          name: Generate Native Code from Expo
          command: npx expo prebuild --clean --no-install
          no_output_timeout: 20m

      - run:
          name: Fix Gradle Properties
          command: |
            chmod +x fastlane/fix-gradle-properties.sh
            ./fastlane/fix-gradle-properties.sh
            
      - run:
          name: Ensure gradlew exists
          command: |
            if [ ! -f "./android/gradlew" ]; then
              echo "gradlew not found! Creating gradle wrapper..."
              cd android
              gradle wrapper
              cd ..
            fi
            chmod +x ./android/gradlew
            
      - run:
          name: Configure Gradle for CI
          command: |
            echo "org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m" >> android/gradle.properties
            echo "org.gradle.caching=true" >> android/gradle.properties
            echo "android.enableJetifier=true" >> android/gradle.properties

      - restore_cache:
          keys:
            - gradle-v1-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}
            - gradle-v1-

      - save_cache:
          key: gradle-v1-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          when: always

      - run:
          name: Deploy to Google Play
          no_output_timeout: 30m
          command: sh fastlane/deploy-android.sh
          
      - store_artifacts:
          path: android/app/build/outputs
          destination: android-build

workflows:
  react-native-android-ios:
    jobs:
      - react-native-test
      - approve_deploy_to_apple_app_store:
          type: approval
          requires:
            - react-native-test
      - approve_deploy_to_google_play_store:
          type: approval
          requires:
            - react-native-test
      - android-build-and-deploy:
          requires:
            - approve_deploy_to_google_play_store
      - macos-build-and-deploy:
          requires:
            - approve_deploy_to_apple_app_store