name: ios-deployment

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development

jobs:
  build:
    runs-on: macos-latest
    environment: ${{ 'test' || github.event.inputs.environment }}
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      P8_AUTH_KEY_BASE64: ${{ secrets.P8_AUTH_KEY_BASE64 }}
      APP_STORE_CONNECT_API_KEY_TEAM_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_TEAM_KEY_ID }}
      APP_STORE_CONNECT_API_KEY_TEAM_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_TEAM_ISSUER_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      ITUNES_TEAM_ID: ${{ secrets.ITUNES_TEAM_ID }}
      APPSTORE_TEAM_ID: ${{ secrets.APPSTORE_TEAM_ID }}
      MATCH_REPO_SSH: ${{ secrets.MATCH_REPO_SSH }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      BASE_URL: ${{ vars.BASE_URL }}
      CI: true
      # Git credentials for match
      GIT_USERNAME: ${{ github.actor }}
      # Automatically provided by GitHub Actions.
      GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # App configuration from .env file
      WORKSPACE: exporeactnativepaper.xcodeproj/project.xcworkspace
      PROJECT: exporeactnativepaper.xcodeproj
      CONFIGURATION: Release
      SCHEME: exporeactnativepaper
      EXPORT_METHOD: app-store
      External_Tests_group_name: ExpoReactNativePaper-Tests

    steps:
      # Sets up the Xcode version
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4.0'

      # Checks out the repository
      - uses: actions/checkout@master

      # Check if SSH key secret exists and has content
      - name: Check if SSH key secret exists
        run: |
          if [ -z "${{ secrets.MATCH_REPO_KEY }}" ]; then
            echo "ERROR: The MATCH_REPO_KEY secret is empty or not set"
            exit 1
          else
            echo "✅ MATCH_REPO_KEY secret exists and has content"
            echo "Length of MATCH_REPO_KEY: $(echo '${{ secrets.MATCH_REPO_KEY }}' | wc -c) characters"
          fi
          
      # Sets up SSH agent with the Match repo private key
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.MATCH_REPO_KEY }}
        continue-on-error: false

      # Test SSH connection to GitHub
      - name: Test SSH connection
        run: |
          ssh -T git@github.com || true
          ssh -vT git@github.com || true

      # Sets up the Ruby version
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
      
      # Cache node_modules
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      # Configure Git for match
      - name: Configure git
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "GitHub CI"
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Installs dependencies using bundle install
      - name: Install Dependencies
        run: |
          cd ios
          bundle install

      # Caches the Pods directory and restores it for future builds
      - uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      # Installs dependencies using npm and pod install
      - name: Setup dependencies
        run: |
          npm install
          cd ios
          pod install

      # Create environment files for fastlane
      - name: Setup environment
        run: |
          cd ios
          # Decode the base64-encoded p8 key and write it to the file
          echo "${{ secrets.P8_AUTH_KEY_BASE64 }}" | base64 --decode > secretKey.p8
          
          # Set the key filepath environment variable
          echo "APP_STORE_CONNECT_API_KEY_KEY_FILEPATH=secretKey.p8" >> $GITHUB_ENV
          
          # Debug - Print environment variables (without revealing secrets)
          echo "Environment Variables Available (redacted):"
          echo "APP_STORE_CONNECT_API_KEY_TEAM_KEY_ID is set: $(if [ -n "$APP_STORE_CONNECT_API_KEY_TEAM_KEY_ID" ]; then echo "yes"; else echo "no"; fi)"
          echo "APP_STORE_CONNECT_API_KEY_TEAM_ISSUER_ID is set: $(if [ -n "$APP_STORE_CONNECT_API_KEY_TEAM_ISSUER_ID" ]; then echo "yes"; else echo "no"; fi)"
          echo "APP_STORE_CONNECT_API_KEY_KEY_FILEPATH is set: $(if [ -n "$APP_STORE_CONNECT_API_KEY_KEY_FILEPATH" ]; then echo "yes"; else echo "no"; fi)"
          echo "WORKSPACE is set: $(if [ -n "$WORKSPACE" ]; then echo "yes"; else echo "no"; fi)"
          echo "PROJECT is set: $(if [ -n "$PROJECT" ]; then echo "yes"; else echo "no"; fi)"
          echo "CONFIGURATION is set: $(if [ -n "$CONFIGURATION" ]; then echo "yes"; else echo "no"; fi)"
          echo "SCHEME is set: $(if [ -n "$SCHEME" ]; then echo "yes"; else echo "no"; fi)"
          echo "EXPORT_METHOD is set: $(if [ -n "$EXPORT_METHOD" ]; then echo "yes"; else echo "no"; fi)"
          
          # Create Matchfile if it doesn't exist
          if [ ! -f fastlane/Matchfile ]; then
            mkdir -p fastlane
            # Extract repo name from SSH URL
            REPO_NAME=$(echo "${{ secrets.MATCH_REPO_SSH }}" | sed -E 's/.*:(.+)\.git/\1/')
            HTTPS_URL="https://github.com/${REPO_NAME}.git"
            echo "Using HTTPS URL for match: ${HTTPS_URL}"
            
            echo 'git_url("'${HTTPS_URL}'")' > fastlane/Matchfile
            echo 'storage_mode("git")' >> fastlane/Matchfile
            echo 'git_basic_authorization(ENV["GIT_BASIC_AUTHORIZATION"])' >> fastlane/Matchfile
            echo 'type("appstore")' >> fastlane/Matchfile
            echo 'app_identifier(["com.mymail.exporeactnativepaper"])' >> fastlane/Matchfile
            echo 'username("'"${{ secrets.APPLE_ID }}"'")' >> fastlane/Matchfile
            echo 'team_id("'"${{ secrets.ITUNES_TEAM_ID }}"'")' >> fastlane/Matchfile
            echo 'readonly(true)' >> fastlane/Matchfile
          fi
      
      # Configure app with BASE_URL
      - name: Configure app environment
        run: |
          # For Expo/React Native, create a .env file with the BASE_URL
          echo "API_URL=${{ vars.BASE_URL }}" > .env
          # If needed, you can also update Info.plist with this URL
          # /usr/libexec/PlistBuddy -c "Set :APIBaseURL ${{ vars.BASE_URL }}" ios/exporeactnativepaper/Info.plist

      # Configure bundle for match password
      - name: Configure bundler
        run: |
          cd ios
          bundle config set --local MATCH_PASSWORD "${{ secrets.MATCH_PASSWORD }}"

      # Builds and deploys the iOS app using Fastlane
      - name: Build and deploy
        run: |
          cd ios
          FASTLANE_HIDE_TIMESTAMP=0 FASTLANE_DISABLE_COLORS=0 FASTLANE_VERBOSE=1 bundle exec fastlane build_and_release --verbose